### ISSUE TITLE
大佬有没有想法折腾下 iPhone 5/6/SE 的屏？

### ISSUE THREAD

**Issue by riclava** [peng-zhihui/HDMI-PI#31]

**Comment by xiebaochun** [comment]
iphone的屏驱动协议是开源的吗？

**Comment by Beiningjun** [comment]
你找错人了嘛？



---原始邮件---
发件人: "Person ***@***.***&gt;
发送时间: 2021年10月11日(周一) 下午2:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [peng-zhihui/HDMI-PI] 大佬有没有想法折腾下 iPhone 5/6/SE 的屏？ (#31)




 
iphone的屏驱动协议是开源的吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
